Repository Team-i-can-do-it/api-server, pull requests merged in 2025-09, with the labels that each got.

#71 [Refactor] 갓챠 뽑기 -> 상점 기획 변경으로 인한 상품 등록 기능 리팩토링
  src/main/java/com/icando/ItemShop/controller/AdminPointShopController.java
  src/main/java/com/icando/ItemShop/controller/UserPointShopController.java
  src/main/java/com/icando/ItemShop/dto/CreateItemRequest.java
  src/main/java/com/icando/ItemShop/entity/Item.java
  src/main/java/com/icando/ItemShop/entity/PointShopHistory.java
  src/main/java/com/icando/ItemShop/exception/PointShopErrorCode.java
  src/main/java/com/icando/ItemShop/exception/PointShopException.java
  src/main/java/com/icando/ItemShop/exception/PointShopSuccessCode.java
  src/main/java/com/icando/ItemShop/repository/ItemRepository.java
  src/main/java/com/icando/ItemShop/service/AdminPointShopService.java
  src/main/java/com/icando/ItemShop/service/UserPointShopService.java
  src/main/java/com/icando/randomBox/controller/RandomBoxController.java
  src/main/java/com/icando/randomBox/entity/RandomBox.java
  src/main/java/com/icando/randomBox/exception/RandomBoxException.java
  src/main/java/com/icando/randomBox/repository/RandomBoxRepository.java
  src/main/java/com/icando/randomBox/service/RandomBoxService.java
  src/test/java/com/icando/ItemShop/PointShopTest.java
  src/test/java/com/icando/randomBox/RandomBoxTest.java
Labels: refactor

#66 [Feat] 자체로그인 기능 구현
  build.gradle
  src/main/java/com/icando/community/post/service/PostService.java
  src/main/java/com/icando/global/auth/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/icando/global/auth/service/JwtService.java
  src/main/java/com/icando/global/auth/util/PasswordUtil.java
  src/main/java/com/icando/global/config/RedisConfig.java
  src/main/java/com/icando/global/config/SecurityConfig.java
  src/main/java/com/icando/member/controller/MemberController.java
  src/main/java/com/icando/member/entity/Member.java
  src/main/java/com/icando/member/entity/Provider.java
  src/main/java/com/icando/member/entity/Role.java
  src/main/java/com/icando/member/exception/MemberSuccessCode.java
  src/main/java/com/icando/member/login/controller/LoginController.java
  src/main/java/com/icando/member/login/dto/JoinDto.java
  src/main/java/com/icando/member/login/dto/JoinResponse.java
  src/main/java/com/icando/member/login/dto/LoginDto.java
  src/main/java/com/icando/member/login/dto/LoginResponse.java
  src/main/java/com/icando/member/login/exception/AuthErrorCode.java
  src/main/java/com/icando/member/login/exception/AuthException.java
  src/main/java/com/icando/member/login/exception/AuthSuccessCode.java
  src/main/java/com/icando/member/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/icando/member/login/handler/LoginFailureHandler.java
  src/main/java/com/icando/member/login/handler/LoginSuccessHandler.java
  src/main/java/com/icando/member/login/service/LoginService.java
  src/main/java/com/icando/member/repository/MemberRepository.java
  src/main/java/com/icando/member/service/MemberService.java
  src/main/java/com/icando/writing/controller/WritingController.java
  src/main/java/com/icando/writing/service/WritingService.java
  src/main/resources/application.yml
Labels: enhancement, feature

#78 [Feature] 상품 상세조회 기능 구현
  src/main/java/com/icando/ItemShop/controller/UserPointShopController.java
  src/main/java/com/icando/ItemShop/dto/ItemResponse.java
  src/main/java/com/icando/ItemShop/exception/PointShopErrorCode.java
  src/main/java/com/icando/ItemShop/exception/PointShopSuccessCode.java
  src/main/java/com/icando/ItemShop/service/UserPointShopService.java
  src/main/java/com/icando/global/config/QuerydslConfig.java
  src/test/java/com/icando/ItemShop/PointShopTest.java
  src/test/java/com/icando/community/PostTest.java
Labels: feature

#80 [Refactor] FeedbackRequest DTO 변경
  src/main/java/com/icando/community/comment/controller/CommentController.java
  src/main/java/com/icando/community/comment/entity/Comment.java
  src/main/java/com/icando/community/comment/repository/CommentRepository.java
  src/main/java/com/icando/community/comment/service/CommentService.java
  src/main/java/com/icando/community/post/controller/PostController.java
  src/main/java/com/icando/community/post/dto/PostCreateRequest.java
  src/main/java/com/icando/community/post/entity/Post.java
  src/main/java/com/icando/community/post/exception/PostException.java
  src/main/java/com/icando/community/post/exception/PostSuccessCode.java
  src/main/java/com/icando/community/post/repository/PostRepository.java
  src/main/java/com/icando/community/post/service/PostService.java
  src/main/java/com/icando/feedback/dto/FeedbackRequest.java
  src/main/java/com/icando/feedback/service/FeedbackService.java
  src/main/java/com/icando/writing/entity/Topic.java
  src/main/java/com/icando/writing/enums/WritingType.java
  src/main/java/com/icando/writing/error/WritingErrorCode.java
  src/main/java/com/icando/writing/error/WritingException.java
  src/main/java/com/icando/writing/service/WritingService.java
  src/test/java/com/icando/feedback/service/FeedbackServiceTest.java
  src/test/java/com/icando/writing/service/TopicServiceTest.java
  src/test/java/com/icando/writing/service/WritingServiceTest.java
Labels: refactor

#79 [Feature] 상품 구매 기능 구현
  src/main/java/com/icando/ItemShop/controller/AdminPointShopController.java
  src/main/java/com/icando/ItemShop/controller/UserPointShopController.java
  src/main/java/com/icando/ItemShop/dto/ItemRequest.java
  src/main/java/com/icando/ItemShop/entity/Item.java
  src/main/java/com/icando/ItemShop/exception/PointShopErrorCode.java
  src/main/java/com/icando/ItemShop/exception/PointShopSuccessCode.java
  src/main/java/com/icando/ItemShop/service/AdminPointShopService.java
  src/main/java/com/icando/ItemShop/service/UserPointShopService.java
  src/main/java/com/icando/member/entity/Member.java
  src/main/java/com/icando/member/entity/Point.java
  src/main/java/com/icando/member/exception/MemberErrorCode.java
  src/main/java/com/icando/member/repository/PointRepository.java
  src/main/resources/application.yml
  src/test/java/com/icando/ItemShop/AdminPointShopTest.java
  src/test/java/com/icando/ItemShop/UserPointShopTest.java
Labels: feature

#81 [Feature] 상점 구매내역 조회 기능 구현
  src/main/java/com/icando/ItemShop/controller/UserPointShopController.java
  src/main/java/com/icando/ItemShop/dto/PointShopHistoryResponse.java
  src/main/java/com/icando/ItemShop/exception/PointShopSuccessCode.java
  src/main/java/com/icando/ItemShop/repository/PointShopHistoryRepository.java
  src/main/java/com/icando/ItemShop/service/UserPointShopService.java
Labels: feature

#85 [Feature] 상품 삭제 기능 구현
  src/main/java/com/icando/ItemShop/controller/AdminPointShopController.java
  src/main/java/com/icando/ItemShop/exception/PointShopSuccessCode.java
  src/main/java/com/icando/ItemShop/service/AdminPointShopService.java
Labels: feature

#97 [Refactor] 상품 조회 필터 하드 코딩 -> enum 클래스 상태값으로 변경
  src/main/java/com/icando/ItemShop/controller/UserPointShopController.java
  src/main/java/com/icando/ItemShop/dto/ItemGetType.java
  src/main/java/com/icando/ItemShop/repository/ItemRepositoryCustom.java
  src/main/java/com/icando/ItemShop/repository/ItemRepositoryImpl.java
  src/main/java/com/icando/ItemShop/service/UserPointShopService.java
  src/main/java/com/icando/member/entity/Point.java
Labels: refactor

#120 [Bug] 피드백 id 업데이트 안됨 버그 해결
  src/main/java/com/icando/feedback/service/FeedbackService.java
  src/main/java/com/icando/writing/entity/Writing.java
Labels: bug

#103 수정사항 반영
  src/main/java/com/icando/global/oauth/OAuthAttributes.java
  src/main/java/com/icando/global/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/icando/global/oauth/services/CustomOAuth2UserService.java
Labels: refactor

#118 [Feature] 북마크 기능 구현
  src/main/java/com/icando/bookmark/controller/BookmarkController.java
  src/main/java/com/icando/bookmark/dto/BookmarkAddRequest.java
  src/main/java/com/icando/bookmark/dto/BookmarkAddResponse.java
  src/main/java/com/icando/bookmark/dto/BookmarkListResponse.java
  src/main/java/com/icando/bookmark/entity/Bookmark.java
  src/main/java/com/icando/bookmark/enums/BookmarkErrorCode.java
  src/main/java/com/icando/bookmark/enums/BookmarkSuccessCode.java
  src/main/java/com/icando/bookmark/exception/BookmarkException.java
  src/main/java/com/icando/bookmark/repository/BookmarkRepository.java
  src/main/java/com/icando/bookmark/service/BookmarkService.java
  src/test/java/com/icando/bookmark/service/BookmarkServiceTest.java
Labels: feature

#125 [Refactor] 문단작성 PagedResponse를 Page로 변경
  src/main/java/com/icando/global/dto/PagedResponse.java
  src/main/java/com/icando/paragraphCompletion/controller/ParagraphCompletionController.java
  src/main/java/com/icando/paragraphCompletion/service/ParagraphCompletionService.java
  src/test/java/com/icando/paragraphCompletion/service/ParagraphCompletionServiceTest.java
Labels: refactor

#129 [Feature] 주제에 타이틀과 설명 추가
  src/main/java/com/icando/writing/controller/WritingController.java
  src/main/java/com/icando/writing/dto/TopicResponse.java
  src/main/java/com/icando/writing/entity/Topic.java
  src/main/resources/data.sql
Labels: feature

#130 [Feature] 단어 완성 피드백 가능하도록 수정
  src/main/java/com/icando/bookmark/controller/BookmarkController.java
  src/main/java/com/icando/feedback/dto/Evaluation.java
  src/main/java/com/icando/feedback/dto/EvaluationFeedback.java
  src/main/java/com/icando/feedback/dto/FeedbackResponse.java
  src/main/java/com/icando/feedback/dto/MbtiScore.java
  src/main/java/com/icando/feedback/entity/Feedback.java
  src/main/java/com/icando/feedback/exception/FeedbackErrorCode.java
  src/main/java/com/icando/feedback/service/FeedbackService.java
  src/main/java/com/icando/paragraphCompletion/controller/ParagraphCompletionController.java
  src/main/java/com/icando/paragraphCompletion/dto/ParagraphCompletionResponse.java
  src/main/java/com/icando/paragraphCompletion/entity/ParagraphCompletion.java
  src/main/java/com/icando/paragraphCompletion/enums/ParagraphCompletionErrorCode.java
  src/main/java/com/icando/paragraphCompletion/repository/ParagraphCompletionRepository.java
  src/main/java/com/icando/paragraphCompletion/service/ParagraphCompletionService.java
  src/main/java/com/icando/writing/service/WritingService.java
  src/test/java/com/icando/feedback/service/FeedbackServiceTest.java
  src/test/java/com/icando/paragraphCompletion/service/ParagraphCompletionServiceTest.java
Labels: feature

#141 [Refactor] Topic 캐싱 처리
  build.gradle
  src/main/java/com/icando/ICanDoApplication.java
  src/main/java/com/icando/writing/repository/TopicRepository.java
  src/main/java/com/icando/writing/service/TopicProvider.java
  src/main/java/com/icando/writing/service/TopicService.java
  src/main/resources/application.yml
  src/main/resources/ehcache.xml
Labels: feature

#144 [Refactor] 회원가입 시, LOCAL로 변경 + 회원탈퇴 시 연관된 엔티티삭제
  src/main/java/com/icando/bookmark/repository/BookmarkRepository.java
  src/main/java/com/icando/member/entity/Member.java
  src/main/java/com/icando/member/login/service/LoginService.java
  src/main/java/com/icando/member/repository/PointHistoryRepository.java
  src/main/java/com/icando/member/service/MemberService.java
  src/main/java/com/icando/paragraphCompletion/repository/ParagraphCompletionRepository.java
  src/main/java/com/icando/writing/repository/WritingRepository.java
  src/test/java/com/icando/ICanDoApplicationTests.java
  src/test/java/com/icando/ItemShop/AdminPointHistoryShopTest.java
  src/test/java/com/icando/ItemShop/UserPointHistoryShopTest.java
  src/test/java/com/icando/feedback/service/FeedbackServiceTest.java
  src/test/java/com/icando/login/LoginTest.java
  src/test/java/com/icando/login/LogoutTest.java
  src/test/java/com/icando/member/mbti/MbtiServiceTest.java
  src/test/java/com/icando/member/mypage/MypageTest.java
  src/test/java/com/icando/writing/service/WritingServiceTest.java
Labels: bug
